---

# First and Last name
my_name:

# Preferred user account  
my_user: 

# Preferred email address
my_email:

# Paid account ngrok auth token  
my_ngrok_authtoken:

# SMTP credentials. It's fine to use your ou email and 4+4 password here.   
my_smtp_authuser: 
my_smtp_authpassword: 
  
# Preferred external domain for site, used to configure nginx reverse
# proxy and ngrok.  This will likely be something like
# $user.lib.ngrok.io The desired domain needs to be configured as a
# reserved wildcard domain in ngrok. Optionally may also want to get
# this subdomain whitelisted with our test CAS server. Contact DevOps
# team for details.
my_httpd_dn_suffix:

# Preferred  SSH broker. For example:
# ssh_brokers:
#   - alias: broker.example.com
#     ip: 127.0.0.1
#     dn_suffix: 'my.internal'
#
ssh_brokers: 

# SSH key to configure for my_user account. 
my_pubkey: 
